### ISSUE TITLE
Equatorial to Galactic and Trig calc PLS

### ISSUE THREAD

**Issue by ARGHouse** [lortordermur/sfcalcsheet#5] opened 2022-10-21 05:21 UTC
I'm working on 3D starmaps in Astrosynth and Pioneer, I usually have to go through around 5 to 10 minutes hopping between my calculator and various online calculators and converters so I can convert Equatorial in to Galactic, and then calculate the trigonomic values so I can get cartesian co-ordinates. Would be handy if this calculator also had an Equatorial to Galactic converter, along with a right angle trig calculator for getting cartesian co-ordinates.

**Comment by jchylik** [comment] 2022-10-31 22:08
And by Equatorial coordinates you mean with respect to equator of Earth, or also equator of some other planets?

**Comment by ARGHouse** [comment] 2022-10-31 22:23
Yep in respect to Earth, RA and Dec.

**Comment by lortordermur** [comment] 2022-10-31 22:24
This is in respect to the equator of Earth. I already found some formulas: [Conversion of coordinates
](https://www.atnf.csiro.au/people/Tobias.Westmeier/tools_coords.php). Also see Google search ["equatorial to galactic coordinates formula"](https://www.google.com/search?q=equatorial+to+galactic+coordinates+formula).

Such a calculator should be doable in SFCalcsheet, although I am a bit weak with trigonometry.

**Comment by jchylik** [comment] 2022-10-31 22:53
> Such a calculator should be doable in SFCalcsheet

It is definitely doable, but the tricky thing is checking in the excel sheet whether the input angle is in degrees or radians.

**Comment by lortordermur** [comment] 2022-10-31 23:02
I would standardize on degrees and include a degree <-> radian converter on the "Conversion" sheet.

**Comment by lortordermur** [comment] 2024-08-14 16:22
I am in the process of finally implementing the calculator but my math skills are not that great in the trigonometry and equations areas. After some tinkering I got the formula for galactic latitude right and the result is correct[^1], however I still don't manage to solve for galactic longitude.

I tried most of the formulas from those sites:[^2][^3][^4] The main matter is that I don't know how to solve for l in the left side of the equation (l - l0).

Here is a work-in-progress copy of the spreadsheet with the interim results visible: [sfcalcsheet.ods](https://github.com/user-attachments/files/16615692/sfcalcsheet.ods)

The versions of the galactic longitude formula are in cells G47-G49 and H49-J49. Maybe someone with better math skills can have a look at it.

[^1]: https://ned.ipac.caltech.edu/coordinate_calculator?in_csys=Equatorial&in_equinox=J2000.0&obs_epoch=2000.0&ra=123d&dec=60d&pa=0.0&out_csys=Galactic&out_equinox=J2000.0
[^2]: https://www.atnf.csiro.au/people/Tobias.Westmeier/tools_coords.php
[^3]: https://aas.aanda.org/articles/aas/full/1998/01/ds1449/node3.html
[^4]: https://astronomy.stackexchange.com/questions/53397/how-can-i-convert-my-sky-coordinate-system-ra-dec-into-galactic-coordinate-sy/53403#53403

**Comment by jchylik** [comment] 2024-08-14 16:58
> The main matter is that I don't know how to solve for l in the left side of the equation (l - l0).

If you mean the equation 10 (section "3.4.2. Transformation"), then it is pretty straightforward. 
The functions arcsin and arccos are both available in majority of Spreadsheets.

For example in Libre Office it is:
=ASIN(  * )
=ACOS(  * )

**Comment by lortordermur** [comment] 2024-08-14 17:09
It is 3.2.1 but the principle is the same.

Yes, I already use ARCSIN/ARCCOS as the inverse operation before I convert to degrees. The issue is the `l - l0` part on the left side of the equals sign in the second and third formula. So far I just add `l0` at the end of the calculation but that doesn't seem to be the correct approach to just have `l` on the left side, i.e. eliminate the `l0`.

**Comment by jchylik** [comment] 2024-08-14 17:13
> The versions of the galactic longitude formula are in cells G47-G49 and H49-J49.

Please, on which sheet is it? I am having a difficulty to find it.

**Comment by lortordermur** [comment] 2024-08-14 17:14
It is on "Conversion", the purple one. Fifth calculator from the top.

**Comment by jchylik** [comment] 2024-08-14 17:22
> It is on "Conversion", the purple one. Fifth calculator from the top.

I have freshly downloaded the latest version, but it does not appear there. The fifth calculator is still Degrees <-> Radians

**Comment by lortordermur** [comment] 2024-08-14 17:24
I linked a work copy of the sheet in a previous issue comment.

https://github.com/lortordermur/sfcalcsheet/issues/5#issuecomment-2289237342

**Comment by jchylik** [comment] 2024-08-14 18:21
I see.

There are a couple of typos, the first one I can see is:

G47 was missing "RADIANS"

> `=DEGREES(ACOS(COS(G46 - G45) * COS(H46) / COS(H47)) + I45)`

`=DEGREES(ACOS(COS(G46 - G45) * COS(H46) / COS(RADIANS(H47))) + I45)
`

I will have a deeper look at it and write more.

**Comment by lortordermur** [comment] 2024-08-14 19:46
Great, if we get the math figured out and the calculator can be implemented I can give you credit in the README if you like.

**Comment by lortordermur** [comment] 2024-08-15 14:44
I got it solved by correcting the formula in J49 (which I had generated using an online solver) to have the H47 value in radians and then converting everything to degrees.

Now working on the reverse calculator. From what I have read that should be doable by keeping the formulas and swapping a few variables around.

Thank you for taking the time to help out. Can I mention you in an acknowledgements section in the README?

**Comment by lortordermur** [comment] 2024-08-15 17:49
@ARGHouse: The converter between equatorial and galactic coordinates is now complete and in the git repo. Any feedback? And how would the calculator for cartesian coordinates work? Do you mean something that makes a vector from RA, Dec and distance and calculates a resulting point in space?

**Comment by ARGHouse** [comment] 2024-08-15 22:39
I'll try it out, thanks.

**Comment by jchylik** [comment] 2024-08-16 11:50
> The converter between equatorial and galactic coordinates is now complete and in the git repo. Any feedback?
 
 I have had a look at it, it works majority of angles, but there is an issue with ((galactic -> equatorial)) for some values on the opposite site of the circle. For example:
 
| b | l | alpha | delta
|--- | --- | --- | --- |
| 0. |  212. | 282.43  |0.82 |
| 0. |  213. | 102.89  |-0.06|
   
   I think it is either due to bounds of used functions, or some typo. I will have a closer look at it.
   
>   Can I mention you in an acknowledgements section in the README?

You can wait with mentioning me until I add the promised calculation of radiation effects on the atmosphere.

**Comment by lortordermur** [comment] 2024-08-16 12:24
Okay. For easier debugging you can make the hidden calculations visible again by unprotecting the Conversion sheet (right-click the tab), selecting the cells and and changing the cell style from "InterimResult" to "StandardBackground".

**Comment by jchylik** [comment] 2024-08-16 13:36
>debugging 

The issue seems to be in the cell G61:
 `=DEGREES(ATAN((COS(G60 - J54)) / (COS(H54) * TAN(H60) - SIN(H54) * SIN(G60 - J54))) + G54)`
 
 Which does not agree with formulas on inverse transform. [^1]
 
 
 [^1]: [Wikipedia: Conversion between equatorial and galactic coordinates](https://en.wikipedia.org/wiki/Galactic_coordinate_system#Conversion_between_equatorial_and_galactic_coordinates)

**Comment by lortordermur** [comment] 2024-08-16 14:20
That is the formula I obtained using an equation solver[^1] from, I think, the third formula under "3.2.2 Transformation" in [^2]. I solved for `α`.

[^1]: https://www.numberempire.com/equationsolver.php
[^2]: https://aas.aanda.org/articles/aas/full/1998/01/ds1449/node3.html

**Comment by lortordermur** [comment] 2024-08-16 14:27
By the way, for it to solve, I had to replace the constants `α0`, `δ0` and `l0` with their numeric values.

**Comment by lortordermur** [comment] 2024-08-16 15:08
Correction: It was formula 6 on page 8 of this PDF file[^1] that I fed into the solver.

Here is [the direct link](https://www.numberempire.com/equationsolver.php?function=tan%28a-192%29%3D%28cos%28l-122%29%29%2F%28tan%28b%29%2Acos%2827%29-sin%2827%29%2Asin%28l-122%29%29&var=a&result_type=false&answers=&_p1=2042).

[^1]: https://sarahspolaor.faculty.wvu.edu/files/d/bff87be8-3998-4745-9a00-7d57560f261d/07_notes.pdf

**Comment by jchylik** [comment] 2024-08-16 15:13
> That is the formula I obtained using an equation solver

I see. You do not have to combine them. Or rather the issue is that by combing the formulas in this way, you kind of remove some information.
(ATAN is defined for all real numbers, but its range of values is only between -π/2 and π/2)

Just as the solver says:
_Warning: some solutions might be lost_

**Comment by lortordermur** [comment] 2024-08-16 15:22
Oops, then by being "lossy" that solver was the only one able to cope with that transformation formula. The Mathway one refused for example.

But there has to be a way to resolve the left side of the formula for `α`.

I am clueless for the moment.

**Comment by jchylik** [comment] 2024-08-16 15:26
> But there has to be a way to resolve the left side of the formula for α.

Yes, there is, but you are losing some of the solutions.

The equation 5 is clear to invert: the values of \delta are always between  -90° and 90°, same as the range of ASIN().

However when you solve the equation 6 the way described in the calculator, you are limiting results only on range between 102° and 282°.

**Comment by jchylik** [comment] 2024-08-16 15:45
... And that is why we need to calculate right hand side of all three equations in 5.2.2  (and btw. in 5.2.1 as well)

- If rhs3 is positive then the solution is `ACOS( rhs2 )+ \alpha_0`
- If rhs3 is negative, then ` 2/π - ACOS( rhs2)+ \alpha_0`

**Comment by lortordermur** [comment] 2024-08-16 15:53
Yes, I counter-checked using the [NED coordinate calculator](https://ned.ipac.caltech.edu/coordinate_calculator) and I see issues with very small values of `b` < 0.48.

So we need an IFS branch with a separate formula for negative and positive values? Could we also limit input to 0-360/0-90 like the NED calculator?

What document/article are you referring to with the paragraphs? Can't find it in my pinned tabs.

**Comment by jchylik** [comment] 2024-08-16 16:27
> So we need an IFS branch with a separate formula for negative and positive values? 

Yes. Either way you need to calculate right hand side of all three equations in 3.2.1 and 3.2.2 [^3]. The linked exercise [^1] just combines them in one.

> Could we also limit input to 0-360/0-90 like the NED calculator?

Could? Yes, but then the calculator would then cover only half of the sky.

[^1]: https://sarahspolaor.faculty.wvu.edu/files/d/bff87be8-3998-4745-9a00-7d57560f261d/07_notes.pdf
[^3]: https://aas.aanda.org/articles/aas/full/1998/01/ds1449/node3.html

**Comment by lortordermur** [comment] 2024-08-16 16:37
Ok, then I will play around a bit with the formula systems (either later or tomorrow) and see what I get. I still need to run them through the solver of course to resolve for the coordinate variables.

**Comment by lortordermur** [comment] 2024-08-17 13:48
Another work-in-progress of the spreadsheet: [sfcalcsheet.ods](https://github.com/user-attachments/files/16645086/sfcalcsheet.ods)

The solved [second](https://www.numberempire.com/equationsolver.php?function=cos%28a-192%29%3Dcos%28l-122%29%2Acos%28b%29%2Fcos%28s%29&var=a&result_type=false&answers=&_p1=2042) and [third](https://www.numberempire.com/equationsolver.php?function=sin%28a-192%29%3D%28sin%28s%29%2Acos%2827%29%2Bcos%28s%29%2Asin%2827%29%2Asin%28a-192%29%29%2Fcos%28b%29&var=a&result_type=false&answers=&_p1=2042) formula of 3.2.2. are in H63 and I63. The first one is already in I61. Do I need to combine those somehow?

If this ends up being too much effort, maybe we can forgo the reverse part of the calculator? It seems to be the less useful part for a worldbuilding spreadsheet and I could release 0.20 then.

**Comment by jchylik** [comment] 2024-08-17 15:14
I can have a look in a few hours when I am back on the keyboard. 
I will also check whether the forward transformation works for most of the angles.

**Comment by jchylik** [comment] 2024-08-19 12:39
I have tried to plot the values from the forward calculator and it has the same issue as the reverse calculator. It works for the angles that you usually test, but all values of `l `always end up between the values 32° and 210°.

Which is not surprising given the used formula `l= -asin ( sin(α - α_0)  cos δ /cos b) +l_0`
Arcsin always returns values between -90° and 90° 
In other words, two different points from the equatorial coordinates and projected to the same point in galactic coordinates. 

I am going to write a fix for both of the calculators soon. 
I will write a quick fix soon.

**Comment by jchylik** [comment] 2024-08-23 14:09
I am back on the topic, there were two issues:

- range of ASIN and ACOS
- the formulas on the link sites often included typos

(Un)surprisingly, the correct equations for transformation[^1] are listed on Wikipedia [^2]

I have tried that the forward and inverse transformation are matching, see:
[sfcalcsheet_mod3exp_test.pdf](https://github.com/user-attachments/files/16729828/sfcalcsheet_mod3exp_test.pdf)

You can see it as a working example: [sfcalcsheet_mod3exp.ods](https://github.com/user-attachments/files/16729814/sfcalcsheet_mod3exp.ods)

The calculations to add to cells:

b [rad]| K56 :
`=ASIN(SIN(RADIANS(E56)) * SIN(H$54) +COS(RADIANS(E56)) * COS(H$54) * COS(RADIANS(C56) - G$54))`

b [deg] | L56 :
`=DEGREES(K56)`

sin(l) | M56 :
`=SIN(RADIANS(C56)-G$54)*COS(RADIANS(E56))/COS(K56)`

cos(l) | N56 :
`=(SIN(RADIANS(E56))*COS($H$54)-COS(RADIANS(E56))*SIN($H$54)*COS(RADIANS(C56)-$G$54))/COS(K56)`

l [rad]| O56 :
`=IF(N56>0,-ASIN(M56)+$I$54,-PI()+ASIN(M56)+$I$54)`

l [deg]| P56 :
`=MOD(DEGREES(O56),360)`



[^1]: Carroll, Bradley; Ostlie, Dale (2007). An Introduction to Modern Astrophysics (2nd ed.). Pearson Addison-Wesley. pp. 900–901. [ISBN](https://en.wikipedia.org/wiki/ISBN_(identifier)) [978-0805304022](https://en.wikipedia.org/wiki/Special:BookSources/978-0805304022).
[^2]: https://en.wikipedia.org/wiki/Galactic_coordinate_system#Conversion_between_equatorial_and_galactic_coordinates

**Comment by jchylik** [comment] 2024-08-23 14:15
And the inverse transformation is then:

δ [rad] | Q61:
`=ASIN(SIN(RADIANS(L61))*SIN(H$54)+COS(RADIANS(L61))*COS(H$54)*COS($I$54-RADIANS(P61) ))`

sin(α) | S61 :
`=COS(RADIANS(L61))*SIN($I$54-RADIANS(P61))/COS(Q61)`

cos(α) | T61 :
`=(SIN(RADIANS(L61))*COS($H$54)-COS(RADIANS(L61))*SIN($H$54)*COS($I$54-RADIANS(P61)))/COS(Q61)`

α [rad] | U61 :
`=IF(T61>0,ASIN(S61)+$G$54,PI()-ASIN(S61)+$G$54)`

**Comment by lortordermur** [comment] 2024-08-23 15:18
Thanks for all your effort! I got error 508 in O56, P56 and U61 because of typos and corrected that. Here is what I got: 
[sfcalcsheet-temp.ods](https://github.com/user-attachments/files/16730559/sfcalcsheet-temp.ods)

Maybe a naive question, but how do I get the calculations into the result fields? When converted to degrees none give the final result.

**Comment by lortordermur** [comment] 2024-08-23 15:34
I think I found that some empty cells are referenced. Looking into it.

**Comment by jchylik** [comment] 2024-08-23 15:35
> Maybe a naive question, but how do I get the calculations into the result fields? When converted to degrees none give the final result.

My bad, the addresses in the reverse transformation were referring to the test sheet, not to the conversion sheet:

**Comment by jchylik** [comment] 2024-08-23 15:37
δ [rad] | Q61:
`=ASIN(SIN(RADIANS(C60))*SIN(H$54)+COS(RADIANS(C60))*COS(H$54)*COS($I$54-RADIANS(E60) ))`

sin(α) | S61 :
`=COS(RADIANS(C60))*SIN($I$54-RADIANS())/COS(Q61)`

cos(α) | T61 :
`=(SIN(RADIANS(C60))*COS($H$54)-COS(RADIANS(C60))*SIN($H$54)*COS($I$54-RADIANS(E60)))/COS(Q61)`

α [rad] | U61 :
`=IF(T61>0,ASIN(S61)+$G$54,PI()-ASIN(S61)+$G$54)`

**Comment by lortordermur** [comment] 2024-08-23 15:38
By the way I made a little mistake in the temp sheet: mod 36 instead of 360 in P56.

**Comment by jchylik** [comment] 2024-08-23 15:41
> I got error 508 in O56, P56
 
 
 That is strange.
 Forward (α,δ) ->  Backward() ->
 worked on all angles with exception of those where δ = -90 or 90 (for obvious reasons).

**Comment by lortordermur** [comment] 2024-08-23 15:43
I googled that and error 508 is simply a bracket or syntax error. Got that sorted out.

**Comment by lortordermur** [comment] 2024-08-23 15:47
RADIANS() in S61 is missing a variable (error 511).

**Comment by jchylik** [comment] 2024-08-23 15:49
> 61 is missing a variable (error 511).

Sorry, it all happened while copying. 

sin(α) | S61 :
`=COS(RADIANS(C60))*SIN($I$54-RADIANS(E60))/COS(Q61)`

**Comment by lortordermur** [comment] 2024-08-23 15:54
Still doesn't quite figure out in terms of results but there are no more errors. Here is what I got in the temp sheet (including degree conversions): [sfcalcsheet-temp.ods](https://github.com/user-attachments/files/16730985/sfcalcsheet-temp.ods)

Could you have a look at it?

**Comment by jchylik** [comment] 2024-08-23 16:00
> Could you have a look at it?

Sure, cells C61 and E61 still refer to the old values, G61 and H61
Instead they should refer to `Degrees(Q61)` and `Mod(Degrees(U61),360)`

**Comment by lortordermur** [comment] 2024-08-23 16:13
Ah, got it. The input values for the galactic coordinates were swapped. Now testing the forward calculator.

**Comment by jchylik** [comment] 2024-08-23 16:17
> Now testing the forward calculator.

Oh, I see what the issue is:
I am off by one row of table.

I refer to C56 and E56 instead of to C55 and E55

**Comment by jchylik** [comment] 2024-08-23 16:26
I have modified directly your sheet and it seems to work now:
[sfcalcsheet-temp-j.ods](https://github.com/user-attachments/files/16731410/sfcalcsheet-temp-j.ods)

**Comment by lortordermur** [comment] 2024-08-23 16:31
Cool, you were a minute faster.

I’ll do some testing, make the interim calculation block a bit more compact and then check it into Git.

After that maybe the cartesian calculator that the OP asked for. That one should be simpler.

**Comment by jchylik** [comment] 2024-08-23 16:36
> maybe the cartesian calculator that the OP asked for. 

Cartesian calculator is simple. Though there is always a question of the units (ly, parsec, ...) and the planet that is a reference point (0,0,0)

**Comment by lortordermur** [comment] 2024-08-23 16:41
SFCalcSheet uses SI units, so I would suggest parsec. It also has a LY <-> parsec converter.

**Comment by lortordermur** [comment] 2024-08-23 16:49
If I use 250 and -45 in the forward and reverse calculators in the file you provided, the `l` and `α` results seem to be off.

**Comment by jchylik** [comment] 2024-08-23 17:08
If I use 250 and -45 in the forward and reverse calculators in the file you provided, the l and α results seem to be off

Oh, I see, the longitude and lattitude were swapped (in the calculation). 
[sfcalcsheet-temp-j2.ods](https://github.com/user-attachments/files/16731780/sfcalcsheet-temp-j2.ods)

**Comment by lortordermur** [comment] 2024-08-23 17:15
Still doesn’t figure out 100% … `l` should be 339.378942 and `α` 65.229915 according to the NED calculator.

**Comment by jchylik** [comment] 2024-08-23 17:21
> Still doesn’t figure out 100% … l should be 339.378942 and α 65.229915 according to the NED calculator.

I am getting the same values in the Spreadsheet as in NED
![screenshot_ned](https://github.com/user-attachments/assets/1dd38bc5-56ad-4b02-87e7-881e1c2cd8e3)

**Comment by lortordermur** [comment] 2024-08-23 17:29
In the j2 file? It somehow shows me different values but if it works for you, I will clean up a bit and check it into Git.
![sfcalcsheet-j2](https://github.com/user-attachments/assets/0928562e-260f-4b39-b1aa-5b859627c700)

**Comment by lortordermur** [comment] 2024-08-23 17:50
Alright, it's in Git. I will release 0.20 tomorrow or on Sunday.

**Comment by jchylik** [comment] 2024-08-25 19:07
> It somehow shows me different values

Well, the values in the screenshot are still those from the formula that you used before.

The C56 in the screenshot is still the value from G56, etc...


> Fixed equatorial <-> galactic converter (see issue #5) 

The Equatorial to Cartesian coordinates works.

**Comment by lortordermur** [comment] 2024-08-25 19:10
Could you have a look at the 0.20 release version? I could then release a 0.20.1 hotfix if necessary.

**Comment by jchylik** [comment] 2024-08-25 19:12
> Could you have a look at the 0.20 release version? I could then release a 0.20.1 hotfix if necessary.

I have had. The forward and backward transformation match only for a certain segment.
Once we insert the values out of the segment, it does not match anymore.
![screenshot_forward_backward](https://github.com/user-attachments/assets/7a31ab1c-6d60-430c-9708-f93a836afaff)

**Comment by jchylik** [comment] 2024-08-25 19:16
You can try to test this:
[sfcalcsheet_25aug_hotfix.ods](https://github.com/user-attachments/files/16741642/sfcalcsheet_25aug_hotfix.ods)

**Comment by lortordermur** [comment] 2024-08-25 19:22
Ok – I fixed the result fields and the hotfix release is on the way.

**Comment by lortordermur** [comment] 2024-08-25 19:41
Hotfix released. Can you verify?

@ARGHouse: Are you satisfied with the new two calculators (equatorial <-> galactic and equatorial to cartesian)? If everything is good the issue can be closed.

**Comment by jchylik** [comment] 2024-08-25 20:20
> Hotfix released. Can you verify?

Yes, I can confirm it works for all quadrants, and matches for backward and forward angles.

Other good news it works even if the user inserts values out of "allowed" range, such as (-370, 100).

**Comment by lortordermur** [comment] 2024-08-25 20:24
Yes, I saw a mod 360 in some cell, that might be why.

This is possibly the first time this complex kind of coordinate conversion has been implemented in a spreadsheet :-)

**Comment by jchylik** [comment] 2024-08-25 21:00
> Yes, I saw a mod 360 in some cell, that might be why.

Not really, I was worried on the inputs. `Mod( *,360)` is applied on the outputs for l and alpha.

> This is possibly the first time this complex kind of coordinate conversion has been implemented in a spreadsheet :-)

Well, not by a long shot. Have you seen some of the macro-economic simulations built within a spreadsheet?
Not to mention pendelum simulator or a full RPG ...
[The 7 most epic Excel creations ever](https://upslide.net/blog/most-amazing-things-you-can-do-in-excel/)

**Comment by lortordermur** [comment] 2024-08-25 21:04
Ah, I already knew about the Japanese man doing impressive art in Excel … but yeah, once you throw BASIC programming in, you can code games and similar.

**Comment by lortordermur** [comment] 2024-09-01 23:13
It seems that we have implemented the requested calculators and did that correctly. Closing issue.

**Closed as completed by lortordermur** 2024-09-01 23:13 UTC
Labels: enhancement
